
spring:
  datasource:
#    driver-class-name: com.mysql.jdbc.Driver
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/jpashop
    username: root
    password: root123!
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        #show_sql: false
        format_sql : true
        default_batch_fetch_size: 1000 #최적화 옵션
    open-in-view: false
  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html
  devtools:
    livereload:
      enabled: true

logging:
  level:
    org.hibernate.SQL: debug
    org.hibernate.type: trace

decorator:
  datasource:
    p6spy:
      enable-logging: true